//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimestoneDigitalTask.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promocode()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public int discount { get; set; }
        public System.DateTime expires_date { get; set; }
        public Nullable<bool> is_used { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
