//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimestoneDigitalTask.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.ProductsShoppingCarts = new HashSet<ProductsShoppingCart>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<int> promocode_id { get; set; }
        public bool is_closed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsShoppingCart> ProductsShoppingCarts { get; set; }
        public virtual Promocode Promocode { get; set; }
    }
}
